### ISSUE TITLE
Air Dash command issues.

### ISSUE THREAD

**Issue by Divineaspect** [ProjectKorra/AvatarMod#82]
Repeated Death and long distance sprinting seemed to disable hotkey recognition when overlapping with vanilla commands in this case Space, also used for jumping. It would fire occasionally but not usually.

This occured with the air dash power.

Upgrading the power to level 4 (double jump) resolved this issue.

Potential mod interactions include the monk mod which affects jump height and running speed.

**Comment by FavouriteDragon** [comment]
I think we fixed this?
Idk if we did

**Comment by Aang23** [comment]
I've just tested and this is not fixed (at least the fact that the keybinds aren't saved).

**Comment by Mahtaran** [comment]
Yeah, the keybinds not being saved is another issue

**Comment by FavouriteDragon** [comment]
@Aang23 Yes please! If you were to test the issue above, that'd be super helpful!

**Comment by Mahtaran** [comment]
Closed due to inactivity
